create table nctable(
stockid char(6) not null,
stockname varchar(12),
indusname varchar(50),
time timestamp not null,
avgcost float default 0.0,
ncgrade float default 0.0,
ncgradeper float default 0.0,
indusinaper float default 0.0,
storate varchar(10),
tgrade float default 0.0,
tgradeper float default 0.0,
priconcost varchar(50),
stocomindex varchar(50),
stocomindus varchar(50),
pseprice float default 0.0,
stdprice float default 0.0,
mgrade float default 0.0,
mgradeper float default 0.0,
mflowto varchar(30),
mflowcomindex varchar(30),
condegree varchar(10),
imgrade float default 0.0,
imgradeper float default 0.0,
ingrade float default 0.0,
ingradeper float default 0.0,
intrend varchar(50),
inrate varchar(10),
bgrade float default 0.0,
bgradeper float default 0.0,
instorate varchar(10),
inprofor varchar(50),
primary key(stockid,time)
);
